### ISSUE TITLE
React on slack notification with merge request status

### ISSUE THREAD

**Issue by eher-werkspot** [codelicia/turbo-enigma#17]
We could have a feature to react to the notification message depending on the status of the merge request:

:pick: draft merge request
:gear: pipeline running
:x: pipeline failed
:green_circle: pipeline is ok
:speech_balloon: has threads to be resolved
:white_check_mark: merge request approved
:rocket: merged

**Comment by EHER** [comment]
We can use this slack method: https://api.slack.com/methods/reactions.add

It requires the timestamp of the original message as a parameter.

**Comment by EHER** [comment]
The message is identified on a Slack channel by its timestamp (sometimes called ts).

We are currently using the Incoming WebHook to notify the channels and this way we are not getting the timestamp back. It's also not possible to send the timestamp on the payload.

So before starting on the reaction itself, we have to find a way to find get the timestamp of a merge request sent earlier.

One way would be by searching on each channel for the message related to the merge request. The benefit of this approach is the avoid dependency on storage. We rely on the services we already have.

Another way would be to change the way we send the message to save the channel and timestamp to use later. This way we have a history of notification but may require some extra service to keep this history available for multiple instances of the application. Redis could be a candidate to keep the history.

**Comment by malukenho** [comment]
The configuration of `turbo-enigma` is getting complicated because users need to create an app in the slack organisation to have a usable token to search messages and react to them.

As we discussed in our slack channel, we could make use of some key/value storage to save the timestamp information. Slack uses the timestamp of each message as a UNIQID, so, if we have the timestamp information and the URL of the merge request saved somewhere, we could refer to it in future updates to the MR quite easily.

**Comment by malukenho** [comment]
https://github.com/codelicia/turbo-enigma/pull/44#discussion_r917668270
